### ISSUE TITLE
Line 49 in utils.groovy is missing brackets

### ISSUE THREAD

**Issue by mariadinkova** [mschuchard/jenkins-devops-libs#11]
It currently is
  if File(dir).exists() {
Due to that Jenkins is throwing an error
I believe it should be
  if (File(dir).exists()) {
Once I fixed it manually -  Jenkins did not threw error for this particular issue

**Comment by mschuchard** [comment]
Groovy syntax checker confirms:

> 49: expecting '(', found 'File' @ line 49, column 6.
     if File(dir).exists() {  
        ^
  1 error

Fix staged for upcoming commit.

**Comment by mschuchard** [comment]
Fixed in 38f6bc1cfe4e790b08b77ed3000b1d10759acf10.
