### ISSUE TITLE
Symlinks for docs

### ISSUE THREAD

**Issue by TheDemonCat** [mschuchard/jenkins-devops-libs#2]
Hello!
Could you please tell me, how does redirect work in symlinks in [TXT documentation files](https://github.com/mschuchard/jenkins-devops-libs/blob/master/vars/faas.txt) ? Do I need to put some kind of plugin?

**Comment by mschuchard** [comment]
It should work automatically, as corroborated in #1. I also [answered a question](https://stackoverflow.com/questions/54590937/jenkinfile-libary-method-documentation/54593194#54593194) on this at SO if that is helpful:

**Comment by TheDemonCat** [comment]
Thank you!
